/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/routes/__root'
import { Route as IndexRouteImport } from './router/routes/index'
import { Route as ProtectedRouteImport } from './router/routes/_protected'
import { Route as SandboxRouteImport } from './router/routes/sandbox'
import { Route as AuthAuthRouteImport } from './router/routes/_auth/auth'
import { Route as ProtectedDashboardRouteImport } from './router/routes/_protected/dashboard'
import { Route as ProtectedInviteTokenRouteImport } from './router/routes/_protected/invite/$token'
import { Route as ProtectedProjectsProjectIdRouteImport } from './router/routes/_protected/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInviteTokenRoute = ProtectedInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectsProjectIdRoute =
  ProtectedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRoute
  '/auth': typeof AuthAuthRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/invite/$token': typeof ProtectedInviteTokenRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRoute
  '/auth': typeof AuthAuthRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/invite/$token': typeof ProtectedInviteTokenRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/_auth/auth': typeof AuthAuthRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/invite/$token': typeof ProtectedInviteTokenRoute
  '/_protected/projects/$projectId': typeof ProtectedProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sandbox'
    | '/auth'
    | '/dashboard'
    | '/invite/$token'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sandbox'
    | '/auth'
    | '/dashboard'
    | '/invite/$token'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/sandbox'
    | '/_auth/auth'
    | '/_protected/dashboard'
    | '/_protected/invite/$token'
    | '/_protected/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SandboxRoute: typeof SandboxRoute
  AuthAuthRoute: typeof AuthAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invite/$token': {
      id: '/_protected/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof ProtectedInviteTokenRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/projects/$projectId': {
      id: '/_protected/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedInviteTokenRoute: typeof ProtectedInviteTokenRoute
  ProtectedProjectsProjectIdRoute: typeof ProtectedProjectsProjectIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedInviteTokenRoute: ProtectedInviteTokenRoute,
  ProtectedProjectsProjectIdRoute: ProtectedProjectsProjectIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SandboxRoute: SandboxRoute,
  AuthAuthRoute: AuthAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
