services:
  # ─── Tests unitaires Api ────────────────────────────────────────
  api-unit-tests:
    build:
      context: ./apps
      dockerfile: Api.Back.UnitTests/Dockerfile.test
    volumes:
      - ./apps:/workspace