FROM node:24-alpine
WORKDIR /app

RUN corepack enable pnpm

ENV PNPM_STORE_DIR=/app/node_modules/.pnpm-store

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY . .

EXPOSE 5173
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]