# ==========================================
# ÉTAPE 1 : L'USINE D'ASSEMBLAGE (Builder)
# ==========================================
FROM node:24-alpine AS builder
WORKDIR /app

RUN corepack enable pnpm
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY . .

# On demande à Vite de compiler tout le code React en HTML/JS minifié
# Le résultat va dans le dossier /app/dist
RUN pnpm run build

# ==========================================
# ÉTAPE 2 : LE SERVEUR WEB (Nginx)
# ==========================================
FROM nginx:alpine

# On copie le code compilé de l'Étape 1 dans le dossier public de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

# Nginx démarre automatiquement
CMD ["nginx", "-g", "daemon off;"]