# ==========================================
# ÉTAPE 1 : BUILD
# ==========================================
FROM node:24-alpine AS builder
WORKDIR /app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml* ./

COPY . .

RUN pnpm install

WORKDIR /app/apps/web-app

RUN pnpm run build

# ==========================================
# ÉTAPE 2 : Nginx
# ==========================================
FROM nginx:alpine

COPY --from=builder /app/apps/web-app/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 80; \
    location / { \
    root /usr/share/nginx/html; \
    index index.html index.htm; \
    try_files $uri $uri/ /index.html; \
    } \
    }' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]