// <auto-generated />
using System;
using Api.Back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618130006_AddProjectTable")]
    partial class AddProjectTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Back.Models.DbIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_identity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date_identity");

                    b.Property<decimal>("CurrentWorkload")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("current_workload_percentage_identity");

                    b.Property<byte[]>("EncryptedProfile")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_profile_blob");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("experience_identity");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname_identity");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted_identity");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Lastname_identity");

                    b.Property<Guid>("PreferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_preferences");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title_identity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date_identity");

                    b.Property<decimal>("WorkloadPoints")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("workload_point_identity");

                    b.HasKey("Id");

                    b.HasIndex("PreferenceId")
                        .IsUnique();

                    b.ToTable("IDENTITIES");
                });

            modelBuilder.Entity("Api.Back.Models.DbPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_preferences");

                    b.Property<string>("Appearance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("appearence_preferences");

                    b.Property<decimal>("FontSize")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("font_size_preferences");

                    b.Property<bool>("IsAutoTheme")
                        .HasColumnType("boolean")
                        .HasColumnName("theme_auto_preferences");

                    b.Property<decimal>("LetterSpacing")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("letter_spacing_preferences");

                    b.Property<string>("Theme")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("theme_preferences");

                    b.HasKey("Id");

                    b.ToTable("PREFERENCES");
                });

            modelBuilder.Entity("Api.Back.Models.DbProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_project");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Api.Back.Models.DbUserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_credential");

                    b.Property<Guid?>("AaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("aa_guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("DescriptorId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("descriptor_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_name");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_identity");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("signature_counter");

                    b.Property<byte[]>("UserHandle")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("user_handle");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("USER_CREDENTIALS");
                });

            modelBuilder.Entity("Api.Back.Models.DbIdentity", b =>
                {
                    b.HasOne("Api.Back.Models.DbPreference", "Preference")
                        .WithOne("Identity")
                        .HasForeignKey("Api.Back.Models.DbIdentity", "PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("Api.Back.Models.DbProject", b =>
                {
                    b.HasOne("Api.Back.Models.DbIdentity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Api.Back.Models.DbUserCredential", b =>
                {
                    b.HasOne("Api.Back.Models.DbIdentity", "Identity")
                        .WithMany("Credentials")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Api.Back.Models.DbIdentity", b =>
                {
                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("Api.Back.Models.DbPreference", b =>
                {
                    b.Navigation("Identity");
                });
#pragma warning restore 612, 618
        }
    }
}
