// <auto-generated />
using System;
using Api.Back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204163501_RenameUserCrendentials")]
    partial class RenameUserCrendentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Back.Models.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_preferences");

                    b.Property<string>("Appearance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("appearence_preferences");

                    b.Property<decimal>("FontSize")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("font_size_preferences");

                    b.Property<bool>("IsAutoTheme")
                        .HasColumnType("boolean")
                        .HasColumnName("theme_auto_preferences");

                    b.Property<decimal>("LetterSpacing")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("letter_spacing_preferences");

                    b.Property<string>("Theme")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("theme_preferences");

                    b.HasKey("Id");

                    b.ToTable("PREFERENCES");
                });

            modelBuilder.Entity("Api.Back.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_users");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date_users");

                    b.Property<decimal>("CurrentWorkload")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("current_workload_percentage_users");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_users");

                    b.Property<string>("Experience")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("experience_users");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firstname_users");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted_users");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified_users");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_users");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash_users");

                    b.Property<Guid>("PreferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_preferences");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title_users");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date_users");

                    b.Property<decimal>("WorkloadPoints")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("workload_point_users");

                    b.HasKey("Id");

                    b.HasIndex("PreferenceId")
                        .IsUnique();

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Api.Back.Models.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_users_crendentials");

                    b.Property<string>("AaGuid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aa_guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("DescriptorId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("descriptor_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("signature_counter");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_handle");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_users");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USERS_CREDENTIALS");
                });

            modelBuilder.Entity("Api.Back.Models.User", b =>
                {
                    b.HasOne("Api.Back.Models.Preference", "Preference")
                        .WithOne("User")
                        .HasForeignKey("Api.Back.Models.User", "PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("Api.Back.Models.UserCredential", b =>
                {
                    b.HasOne("Api.Back.Models.User", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Back.Models.Preference", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Back.Models.User", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
