FROM mcr.microsoft.com/dotnet/sdk:10.0
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
WORKDIR /app

COPY Api.Back.csproj .
RUN dotnet restore

COPY . .

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:8080"]