FROM mcr.microsoft.com/dotnet/sdk:10.0 AS builder

WORKDIR /app

COPY Api.Back.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /out


FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app

USER app

COPY --from=builder --chown=app:app /out .

EXPOSE 8080


ENTRYPOINT ["dotnet", "Api.Back.dll"]