FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN groupadd -r dotnetgroup \
    && useradd -r -m -d /home/dotnetuser -g dotnetgroup dotnetuser

WORKDIR /app
RUN chown -R dotnetuser:dotnetgroup /app

USER dotnetuser

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/home/dotnetuser/.dotnet/tools"

ENV DOTNET_NOLOGO=true
ENV DOTNET_CLI_TELEMETRY_OPTOUT=true
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

COPY --chown=dotnetuser:dotnetgroup Api.Back.csproj .
RUN dotnet restore

COPY --chown=dotnetuser:dotnetgroup . .

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:8080"]