name: CI TaskForce

on:
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - "**.md"
      - ".vscode/**"
  pull_request:
    branches: ["main", "dev"]

jobs:
  # --- BACKEND C# ---
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          dotnet-version: 10.0.x

      - name: Cache NuGet
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

      - name: Restore
        run: dotnet restore taskforce.sln

      - name: Build
        run: dotnet build apps/Api.Back/Api.Back.csproj --no-restore --configuration Release

      - name: Run Unit Tests with coverage
        run: dotnet test apps/Api.Back.UnitTests/Api.Back.UnitTests.csproj --no-restore --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Security scan
        run: |
          OUTPUT=$(dotnet list package --vulnerable --include-transitive 2>&1)
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q -i "critical\|high"; then
            echo "Vulnérabilités critiques détectées !"
            exit 1
          fi

  # --- FRONTEND REACT & ASTRO ---
  build-web-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Security audit
        run: pnpm audit --audit-level=high
        continue-on-error: true

      - name: Type Check
        run: pnpm --filter web-app exec tsc --noEmit

      - name: Lint Check
        run: pnpm --filter web-app exec eslint . --max-warnings=0

      - name: Build React App
        run: pnpm --filter web-app build

      - name: Build Landing Page
        run: pnpm --filter landing-page build

  # --- SECURITE GLOBALE ---
  security-scan:
    runs-on: ubuntu-latest
    needs: [build-backend, build-web-apps]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@c07df6fec6fa692e6fd1200d50aaa1fdd66f03c8
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'